### PR TITLE
Update GUIDE.md for latest Raspbian & TF

### PR DESCRIPTION
**Pull request by grassgit**
Updated for latest version of tensorflow and raspbian Strech.

- Remove to superseeded steps
- Added step to replace Eigen dependency

### CODE REVIEW

**Comment by JAICHANGPARK** [comment]
@grassgit  thank you

**Comment by kaskavalci** [comment]
@grassgit can you share your python wheel file for latest tensorflow?

**Comment by grassgit** [comment]
You can download the raspberry Strech wheel here: 
https://www.dropbox.com/s/svwrkzed7vqcmyv/tensorflow-1.3.0-cp35-cp35m-linux_armv7l.whl?dl=0 (~37Mb)

**Comment by samjabrahams** [comment]
Sorry for being away forever- I can't verify this locally, but I'll trust the community that this works properly. Thanks for making this!

**Pull request merged**
